/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsletterBasicGoodGreatRouteImport } from './routes/newsletter.basic-good-great'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterBasicGoodGreatRoute =
  NewsletterBasicGoodGreatRouteImport.update({
    id: '/basic-good-great',
    path: '/basic-good-great',
    getParentRoute: () => NewsletterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/newsletter/basic-good-great': typeof NewsletterBasicGoodGreatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/newsletter/basic-good-great': typeof NewsletterBasicGoodGreatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/newsletter/basic-good-great': typeof NewsletterBasicGoodGreatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/newsletter'
    | '/sitemap.xml'
    | '/newsletter/basic-good-great'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newsletter' | '/sitemap.xml' | '/newsletter/basic-good-great'
  id:
    | '__root__'
    | '/'
    | '/newsletter'
    | '/sitemap.xml'
    | '/newsletter/basic-good-great'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsletterRoute: typeof NewsletterRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/basic-good-great': {
      id: '/newsletter/basic-good-great'
      path: '/basic-good-great'
      fullPath: '/newsletter/basic-good-great'
      preLoaderRoute: typeof NewsletterBasicGoodGreatRouteImport
      parentRoute: typeof NewsletterRoute
    }
  }
}

interface NewsletterRouteChildren {
  NewsletterBasicGoodGreatRoute: typeof NewsletterBasicGoodGreatRoute
}

const NewsletterRouteChildren: NewsletterRouteChildren = {
  NewsletterBasicGoodGreatRoute: NewsletterBasicGoodGreatRoute,
}

const NewsletterRouteWithChildren = NewsletterRoute._addFileChildren(
  NewsletterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsletterRoute: NewsletterRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
